### ISSUE TITLE
QuakeEX.kpf overrides custom modification menu graphics

### ISSUE THREAD

**Issue by Xylemon** [fte-team/fteqw#167]
If you have the "QuakeEX.kpf" data installed from the remaster, the included menu graphics are always overriding any custom menu graphics modification may have. This is because QuakeEX.kpf needs to be in the root folder alongside id1 and the like. FTE's menu should have a check to see if a mod has any custom menu assets and load those instead.

**Comment by Shpoike** [comment]
FTE explicitly favours the use of QE's or QRP's menufont over mod artwork, if only because this avoids the ugly results when FTE's extra menu options are unable to use the same baked fonts as the mod's artwork uses. Frankly its ugly either way and using QE's at least allows for localisation without needing to create mutually-exclusive language packs etc.

The fact that quakeex.kpf is in the basedir is irrelevant here, FTE will load the same replacements if its renamed to id1/pak1.pk3 or whatever. This should help highlight that mods are free to provide replacement fonts etc, at least for FTE users. Actual QE users will likely find themselves unable to override the font/etc as part of their mods (as well as half the users accidentally using the ugly accessibility fonts).

QE content should generally be kept separate from non-QE content, if only because various map differences will result in multiplayer incompatibility - steam provides two separate basedirs for a reason!

**Comment by eukara** [comment]
For my purposes, `QuakeEX.kpf` I moved to `mg1/game0.pk3` which will allow other clients to connect just fine.

The menu is nicer with a dedicated 'Mods' and 'Updates' buttons, but for the mods that override menu assets it ends up looking worse. Perhaps a cvar controlled override would be a decent compromise. Or, simply detect if a mod overrides the main buttons .lmp file and disable the QuakeEX.kpf menu.

**Comment by eukara** [comment]
Addressed with this commit https://github.com/fte-team/fteqw/commit/e20ee6c8544f2582c6f5d42a0cdc40e7342a8878
