### ISSUE TITLE
Dimension of the Machine's start map VIS woes

### ISSUE THREAD

**Issue by Xylemon** [fte-team/fteqw#168]
The new remaster episode has two grates on the start map that don't render correctly, yet for some reason two other identical ones in the same room render fine. It could be an issue with how FTE is reading the VIS data in the map, but that is merely a guess. Doing r_novis 1 "fixes" the issue at the cost of framerate but showcases how it's probably VIS related.

Pictured: The one on the left works while the one on the right produces the hall of mirrors effect.
![fte-20230419220957-0](https://user-images.githubusercontent.com/7539500/233266196-7184c175-88bf-4f38-91b5-90873493f0a6.png)

**Comment by eukara** [comment]
Quoted from my comment on Fedi:

> That's how the map is built, apparently. They use transparent textures on world brushes (blocking visibility in normal Quake). The re-release engine presumably does culling on the GPU directly and thus doesn't need to walk the vis tree. I know - blasphemy! But it might be better for larger maps like the ones found in mg1. There's some solutions you can use for the time being but they're suboptimal. Such as disabling vis (cvar: `r_novis`) in combination with enabling the scene cache (cvar: `r_scenecache`), however lightmap updates are still handled on the CPU so it might not cut it for every map.

**Comment by Shpoike** [comment]
fence textures are not meant to be baked into the worldmodel like that, specifically because the vis tool will think that they are still fully opaque and thus the resulting vis claims that the surfaces behind cannot be visible - except they can because of it being a fence texture.
this makes it a content bug rather than an engine one. its just unfortunate that the map was made for an engine that throws the entire map at the gpu in one go instead of obeying the pvs info.
