### ISSUE TITLE
How to rotate maps in QW using FTEQW?

### ISSUE THREAD

**Issue by paulogagliardi** [fte-team/fteqw#182]
Hi, friends! =)

I am trying to setup a FFA Quake World server with FTE, running additional maps with the command line:

./fteqw-sv +sv_port 27500 -game ffa -noexit -dedicated 16 +exec rotate.cfg

The rotate.cfg file has a several maps like:

aerowalk [initial map]
pim3
q1edge

... but, when the map aerowalk is ended, the server goes to the start and not to pim3 like expected.

Why not?

How can I correctly rotate maps in FTEQW? Please...

**Comment by eukara** [comment]
Hello! That's something the game logic generally implements.
Server admins commonly use projects like https://github.com/QW-Group/ktx for features like that. Older Quake/QW progs sometimes implement their own type of map cycle/rotation too. Basically, it's something done in the progs.dat/qwprogs.dat that your mod is running. 
If you have the vanilla QuakeWorld progs, I guess I can show how to add support for map rotation via means of QuakeC.

You might want to look into ktx first anyway, since it can do a whole lot more you might want too.

**Comment by paulogagliardi** [comment]
Hey, eucara!

OK.

In fact, I had already configured a KTX server. But using MVDSV.

But... my intention with FTEQW would be to build a server that would accept QW and NQ clients and unite the both worlds. A server with several additional maps.

Please, if it is possible, I would really like to know how to do map rotation via QuakeC. I also have a mod here called Total Destruction (running with fteqw) that could use this map rotation as well (https://github.com/paulogagliardi/td2qw).

Thanks for your attention. =)

**Comment by eukara** [comment]
Here you go! https://github.com/eukara/td2qw/commit/8da82704e887b782e882f847a226153ae5b63048

All you have to do in order to trigger a level change is to issue `nextmap` in console. In this fork, I've made it so that it issues that command whenever the level is over.

You can set which mapcycle to use via the `mapcycle_file` console variable. The default is 'mapcycle.txt'

For testing I simply made the following mapcycle.txt file:

```
dm1
dm2
dm3
dm4
dm5
dm6
```

And that's about all there is to say! Hope this helps.

**Comment by paulogagliardi** [comment]
Ok!
I understanded what you did.
I cloned your repository. But, when I tried to build, it gives me an error:

compiling mapcycle.qc
at global scope,
mapcycle.qc:8: error: "optional" is not a type
mapcycle.qc:9: error: "optional" is not a type
mapcycle.qc:11: error: ":" is not a type
in function Mapcycle_Load (line 20),
mapcycle.qc:20: error: Parameter is not named

************ ERROR ************
Errors have occured

Error in mapcycle.qc on line 76

Although I've done some modifications in this repository, I do not master 100% the QuakeC language. I investigated the source code, but have no ideas about this error.

Did you compile and not received errors?

**Comment by eukara** [comment]
Seems like you're using an old version of fteqcc, since it doesn't detect the `optional` keyword.  Can you try a build from https://www.fteqcc.org/ and try again?

**Comment by paulogagliardi** [comment]
WOW, you're right! o.O
My FTEQCC for Windows was a 2016 version.
(But my FTE Linux should be updated... I tried by Linux too and it gives me the same error) I will investigate it later. Maybe I will need to build FTEQCC Linux again. 

OK! It works! It builded!
Now I am doing the tests and report you later.
Thanks! I really appreciated your help! Helped me a lot!

**Comment by eukara** [comment]
No problem! If you need any more QC help or general advice you know where to ping! :D
