### ISSUE TITLE
I want new "GIVE A" cheat command for Quake One only

### ISSUE THREAD

**Issue by FeatureRequestor** [fte-team/fteqw#239]
As how the "GIVE H" cheat command is used to set player's health to any number the cheater wants on Quake One, the "GIVE A" cheat command is used to set player's armor to any number the cheater wants on Quake One.

**Comment by Xylemon** [comment]
I am going to close as we already multiple issues (#85 #89 and #90) about this CVAR.

Since FTEQW is a multi game engine, game specific CVARs can cause conflicts if we add it to the base engine rather than a plugin (like Quake 3). For example, there could be a Quake 2 mod that has the same exact CVAR but doesn't function or worse breaks the mod.

Sorry  if this isn't the answer you were looking for, but opening another issue on the matter isn't going to change our mind.

**Comment by FeatureRequestor** [comment]
> I am going to close as we already multiple issues (#85 #89 and #90) about this CVAR.
> 
> Since FTEQW is a multi game engine, game specific CVARs can cause conflicts if we add it to the base engine rather than a plugin (like Quake 3). For example, there could be a Quake 2 mod that has the same exact CVAR but doesn't function or worse breaks the mod.
> 
> Sorry if this isn't the answer you were looking for, but opening another issue on the matter isn't going to change our mind.

If that so then I will NEVER play Quake with FTEQW anymore.
From now on I am playing Quake with Zircon because Zircon also supports real time lighting and shadows, reflections, refractions, realistic water and even the GIVE A command.

GOOD BYE FOREVER

**Comment by perondeidad** [comment]
> If that so then I will NEVER play Quake with FTEQW anymore.
> 
> From now on I am playing Quake with Zircon because Zircon also supports real time lighting and shadows, reflections, refractions, realistic water and even the GIVE A cheat command.
> 
> I QUIT FTEQW FOREVER GOOD BYE FOREVER

El giga-ardido

**Comment by Xylemon** [comment]
While I agree they were disrespectful, we don't need to dwell or pile on. So I will be locking the conversation.

Since I am locking, if anyone wants this cheat, it probably would be better suited in a CSQC addon as it's messy to shove it into the engine directly. You can also put it in a Quake 1 plugin for FTEQW perhaps, but I think CSQC just makes more sense. Feel free to open a PR to anyone who wants this.
