### ISSUE TITLE
where are fteqw configs located?

### ISSUE THREAD

**Issue by solarite1797** [fte-team/fteqw#257]
id like to import my configs from darkplaces (binds, fov, video settings, etc) 
thanks

**Comment by solarite1797** [comment]
+ why does my display gamma get reset to default when i tab out or quit the game i have to press win ctrl shift b to reset it

**Comment by Xylemon** [comment]
Hi sorry for the delayed response, I see you closed the issue but felt you should have your questions answered.

> id like to import my configs from darkplaces (binds, fov, video settings, etc) thanks

Since you are coming from DarkPlaces, you can keep the configs in your `id1` folder if you have them there already and just run in console `exec example.cfg`. You may experience side effects since there are some differences between the engines as not every CVAR (setting) will be identical. When you save your config (either in the menu or `cfg_save` in console) FTE will generally store a new unique config file called `fte.cfg` in a folder alongside `id1` called `fteq1`. To see what directories are being read or written to just type `path` in console.

> * why does my display gamma get reset to default when i tab out or quit the game i have to press win ctrl shift b to reset it

This could be caused by the default gamma compatibility behavior for older hardware. Try setting in console `vid_hardwaregamma 2` and see if it fixes the issue.

Hope that was helpful.
